<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>E-values for unmeasured confounding • EValue</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><link href="../extra.css" rel="stylesheet">
<meta property="og:title" content="E-values for unmeasured confounding">
<meta property="og:description" content="EValue">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">EValue</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">2.0.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../reference/index.html">All functions</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Unmeasured confounding
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/unmeasured-confounding.html">Examples</a>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Articles</a>
      <ul class="dropdown-menu" role="menu">
<li>
          <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4820664/">Sensitivity analysis without assumptions</a>
        </li>
        <li>
          <a href="http://annals.org/aim/article-abstract/2643434/sensitivity-analysis-observational-research-introducing-e-value?doi=10.7326%2fM16-2607">Sensitivity analysis in observational research: Introducing the E-value</a>
        </li>
        <li>
          <a href="https://journals.lww.com/epidem/Fulltext/2018/09000/Web_Site_and_R_Package_for_Computing_E_values.26.aspx">Website and R package for computing E-values</a>
        </li>
        <li>
          <a href="https://annals.org/aim/article-abstract/2719984/correcting-misinterpretations-e-value">Correcting misinterpretations of the E-value</a>
        </li>
        <li>
          <a href="https://biostats.bepress.com/harvardbiostat/paper215/">Technical considerations in the use of the E-value</a>
        </li>
      </ul>
</li>
    <li>
      <a href="https://www.evalue-calculator.com">E-value calculator</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Multiple biases
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/multiple-bias.html">Introduction</a>
    </li>
    <li>
      <a href="../articles/multiple-bias-examples.html">Examples</a>
    </li>
    <li>
      <a href="https://arxiv.org/abs/2005.02908">Article</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Meta-analysis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="https://www.tandfonline.com/doi/full/10.1080/01621459.2018.1529598">Article</a>
    </li>
    <li>
      <a href="https://mmathur.shinyapps.io/meta_gui_2/">Calculator</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Selection bias
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Articles</a>
      <ul class="dropdown-menu" role="menu">
<li>
          <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6553568/pdf/ede-30-509.pdf">Bounding bias due to selection</a>
        </li>
        <li>
          <a href="https://journals.lww.com/epidem/Citation/9000/Simple_sensitivity_analysis_for_control_selection.98406.aspx">Simple sensitivity analysis for control selection bias</a>
        </li>
      </ul>
</li>
    <li>
      <a href="http://selection-bias.louisahsmith.com">Calculator</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>E-values for unmeasured confounding</h1>
            
      
      
      <div class="hidden name"><code>unmeasured-confounding.Rmd</code></div>

    </div>

    
    
<div id="examples-from-sensitivity-analysis-without-assumptions" class="section level2">
<h2 class="hasAnchor">
<a href="#examples-from-sensitivity-analysis-without-assumptions" class="anchor"></a>Examples from <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4820664/"><em>Sensitivity Analysis without Assumptions</em></a>
</h2>
<p>Hammond and Horn<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> estimated that cigarette smoking increased the risk of lung cancer by more than 10-fold. Fisher proposed that genetic confounding may explain all of the apparent association.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> We can calculate the magnitude of confounding that would be necessary to fully explain the estimated risk ratio of 10.73 (95% CI 8.02, 14.36):</p>
<div class="sourceCode" id="cb1"><html><body><pre class="r"><span class="fu"><a href="../reference/evalues.RR.html">evalues.RR</a></span>(<span class="kw">est</span> <span class="kw">=</span> <span class="fl">10.73</span>, <span class="kw">lo</span> <span class="kw">=</span> <span class="fl">8.02</span>, <span class="kw">hi</span> <span class="kw">=</span> <span class="fl">14.36</span>)</pre></body></html></div>
<pre class="output"><code>#&gt;             point    lower upper
#&gt; RR       10.73000  8.02000 14.36
#&gt; E-values 20.94777 15.52336    NA</code></pre>
<p>The E-value of 20.95 tells us that a confounder, or set of confounders, such as that proposed by Fisher, would have to be associated with a 20-fold increase in the risk of lung cancer, and must be 20 times more prevalent in smokers than non-smokers, to explain the observed risk ratio. If the strength of one of these relationships were weaker, the other would have to be stronger for the causal effect of smoking on lung cancer to be truly null.</p>
<p>To see how the magnitude of the exposure-confounder and the confounder-outcome relationships would have to vary to fully explain the observed assocation, we can use the <code><a href="../reference/bias_plot.html">bias_plot()</a></code> function:</p>
<div class="sourceCode" id="cb3"><html><body><pre class="r"><span class="fu"><a href="../reference/bias_plot.html">bias_plot</a></span>(<span class="fl">10.73</span>, <span class="kw">xmax</span> <span class="kw">=</span> <span class="fl">40</span>)</pre></body></html></div>
<p><img src="unmeasured-confounding_files/figure-html/unnamed-chunk-3-1.png" width="700"></p>
<p>This tells us, for example, that if the exposure-confounder parameter (<span class="math inline">\(RR_{EU}\)</span>) were 15, meaning that the confounder(s) is 15 times more likely among smokers, the (<span class="math inline">\(RR_{UD}\)</span>) parameter would have to be about 40 for it to even be possible that confounding explains the entire observed association.</p>
<p>We could also plot the lower bound of the confidence interval, which we calculated an E-value of 15.52 for above.</p>
<div class="sourceCode" id="cb4"><html><body><pre class="r"><span class="fu"><a href="../reference/bias_plot.html">bias_plot</a></span>(<span class="fl">8.02</span>, <span class="kw">xmax</span> <span class="kw">=</span> <span class="fl">40</span>)</pre></body></html></div>
<p><img src="unmeasured-confounding_files/figure-html/unnamed-chunk-4-1.png" width="700"></p>
<p>We can also calculate an E-value for shifting an estimate to a number other than the null. For example to reduce an observed relative risk of 2.5 to a true causal relative risk of 1.5, the E-value is:</p>
<div class="sourceCode" id="cb5"><html><body><pre class="r"><span class="co"># summary() used to print the E-value only</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span>(<span class="fu"><a href="../reference/evalues.RR.html">evalues.RR</a></span>(<span class="kw">est</span> <span class="kw">=</span> <span class="fl">2.5</span>, <span class="kw">true</span> <span class="kw">=</span> <span class="fl">1.5</span>))</pre></body></html></div>
<pre class="message"><code>#&gt; You are calculating a "non-null" E-value, i.e., an E-value for the
#&gt; minimum amount of unmeasured confounding needed to move the estimate
#&gt; and confidence interval to your specified true value rather than to the
#&gt; null value.</code></pre>
<pre class="output"><code>#&gt; [1] 2.720759</code></pre>
</div>
<div id="examples-from-sensitivity-analysis-in-observational-research-introducing-the-e-value" class="section level2">
<h2 class="hasAnchor">
<a href="#examples-from-sensitivity-analysis-in-observational-research-introducing-the-e-value" class="anchor"></a>Examples from <a href="http://annals.org/aim/article-abstract/2643434/sensitivity-analysis-observational-research-introducing-e-value?doi=10.7326%2fM16-2607"><em>Sensitivity Analysis in Observational Research: Introducing the E-value</em></a>
</h2>
<p>A study by Victora et al. examing the relationship between breastfeeding and infant death by respiratory infection, finding that mortality was increased by a factor of 3.9 (95% CI 1.8, 8.7) among infants with with only formula.<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> However, smoking, which was not assessed in this study, may be a confounder. We can calculate E-values for the point estimate and the confidence interval:</p>
<div class="sourceCode" id="cb8"><html><body><pre class="r"><span class="fu"><a href="../reference/evalues.OR.html">evalues.OR</a></span>(<span class="kw">est</span> <span class="kw">=</span> <span class="fl">3.9</span>, <span class="kw">lo</span> <span class="kw">=</span> <span class="fl">1.8</span>, <span class="kw">hi</span> <span class="kw">=</span> <span class="fl">8.7</span>, <span class="kw">rare</span> <span class="kw">=</span> <span class="fl">TRUE</span>)</pre></body></html></div>
<pre class="output"><code>#&gt;             point lower upper
#&gt; RR       3.900000   1.8   8.7
#&gt; E-values 7.263034   3.0    NA</code></pre>
<p>We can also plot the magnitude of each of the parameters that would be required to explain away the point estimate:</p>
<div class="sourceCode" id="cb10"><html><body><pre class="r"><span class="fu"><a href="../reference/bias_plot.html">bias_plot</a></span>(<span class="fl">3.9</span>, <span class="kw">xmax</span> <span class="kw">=</span> <span class="fl">20</span>)</pre></body></html></div>
<p><img src="unmeasured-confounding_files/figure-html/unnamed-chunk-7-1.png" width="700"></p>
<p>The next example concerns a study by the Agency for Healthcare Research and Quality, which found that breastfeeding decreased the risk of childhood leukemia.<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a> The article reported an RR of 0.80 (95 % CI 0.71, 0.91). This example demonstrates that we can calculate E-values for protective factors as well.</p>
<div class="sourceCode" id="cb11"><html><body><pre class="r"><span class="fu"><a href="../reference/evalues.RR.html">evalues.RR</a></span>(<span class="kw">est</span> <span class="kw">=</span> <span class="fl">0.80</span>, <span class="kw">lo</span> <span class="kw">=</span> <span class="fl">0.71</span>, <span class="kw">hi</span> <span class="kw">=</span> <span class="fl">0.91</span>)</pre></body></html></div>
<pre class="output"><code>#&gt;             point lower    upper
#&gt; RR       0.800000  0.71 0.910000
#&gt; E-values 1.809017    NA 1.428571</code></pre>
</div>
<div class="footnotes">
<hr>
<ol>
<li id="fn1"><p>Hammond EC, Horn D. Smoking and death rates: report on forty four months of follow-up of 187,783 men. J Am Med Assoc. 1958;166:1159– 1172, 1294–1308.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>Fisher RA. Dangers of cigarette smoking [letter]. Brit Med J. 1957;2:297– 298.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>Victora CG, Smith PG, Vaughan JP, Nobre LC, Lombardi C, Teix- eira AM, et al. Evidence for protection by breast-feeding against in- fant deaths from infectious diseases in Brazil. Lancet. 1987;2:319-22.<a href="#fnref3" class="footnote-back">↩︎</a></p></li>
<li id="fn4"><p>Ip S, Chung M, Raman G, Chew P, Magula N, DeVine D, et al. Breastfeeding and Maternal and Infant Health Outcomes in Devel- oped Countries. Evidence Report/Technology Assessment no. 153. (Prepared by Tufts-New England Medical Center Evidence-based Practice Center under contract no. 290-02-0022.) AHRQ publication no. 07-E007. Rockville: Agency for Healthcare Research and Quality; April 2007.<a href="#fnref4" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by <a href="https://mayamathur.com">Maya B. Mathur</a>, <a href="https://sites.google.com/site/pengdingpku/">Peng Ding</a>, <a href="https://louisahsmith.com">Louisa H. Smith</a>, <a href="https://www.hsph.harvard.edu/tyler-vanderweele/">Tyler J. VanderWeele</a>.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
